version: '3.8'

services: 
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - main_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  main_pg_data:

