version: '3.8'

services:
  app:
    build: ./app/
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:5.0.11-ubi8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db

volumes:
  data_db: