version: '3.8'

services:
  app:
    build: ./app/
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0.14-ubi8-20240821T091142Z
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
